# Nexus 4
add_lunch_combo revolt_mako-userdebug
# Grouper
add_lunch_combo revolt_grouper-userdebug
# I9100
add_lunch_combo revolt_i9100-userdebug
# I9100G
add_lunch_combo revolt_i9100g-userdebug
# Maguro
add_lunch_combo revolt_maguro-userdebug
# N7000
add_lunch_combo revolt_n7000-userdebug
# N7100
add_lunch_combo revolt_n7100-userdebug
# I9300
add_lunch_combo revolt_i9300-userdebug
# D710
add_lunch_combo revolt_d710-userdebug
# I9500
add_lunch_combo revolt_i9500-userdebug
# Find5
add_lunch_combo revolt_find5-userdebug
# Jfltetmo
add_lunch_combo revolt_jfltetmo-userdebug
# Jfltecan
add_lunch_combo revolt_jfltecan-userdebug
# JFlteusc
add_lunch_combo revolt_jflteusc-userdebug
# M7
add_lunch_combo revolt_m7-userdebug
# N8000
add_lunch_combo revolt_n8000-userdebug
