add_lunch_combo revolt_mako-userdebug
add_lunch_combo revolt_grouper-userdebug
add_lunch_combo revolt_i9100-userdebug
add_lunch_combo revolt_i9100g-userdebug
#add_lunch_combo revolt_n7000-userdebug
#add_lunch_combo revolt_n7100-userdebug
#add_lunch_combo revolt_i9300-userdebug
