PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/d2lte.mk \
    $(LOCAL_DIR)/d710.mk \
    $(LOCAL_DIR)/deb.mk \
    $(LOCAL_DIR)/find5.mk \
    $(LOCAL_DIR)/flo.mk \
    $(LOCAL_DIR)/grouper.mk \
    $(LOCAL_DIR)/i9100.mk \
    $(LOCAL_DIR)/i9100g.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/i9500.mk \
    $(LOCAL_DIR)/jflte.mk \
    $(LOCAL_DIR)/m7.mk \
    $(LOCAL_DIR)/m8.mk \
    $(LOCAL_DIR)/mb886.mk \
    $(LOCAL_DIR)/maguro.mk \
    $(LOCAL_DIR)/mako.mk  \
    $(LOCAL_DIR)/manta.mk \
    $(LOCAL_DIR)/n7000.mk \
    $(LOCAL_DIR)/n7100.mk \
    $(LOCAL_DIR)/n8000.mk \
    $(LOCAL_DIR)/n8010.mk \
    $(LOCAL_DIR)/n8013.mk \
    $(LOCAL_DIR)/odin.mk \
    $(LOCAL_DIR)/pico.mk \
    $(LOCAL_DIR)/vs980.mk \
    $(LOCAL_DIR)/xt907.mk \
    $(LOCAL_DIR)/xt925.mk \
    $(LOCAL_DIR)/xt926.mk \
    $(LOCAL_DIR)/yuga.mk
